apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "demoapp"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:841726648246:certificate/835bee94-b2d4-471d-af94-89d4d8e67b53
  labels:
    app: demoapp
spec:
  rules:
    - host: discoveringthecloud.com
      http:
        paths:
          - path: /summer
            backend:
              serviceName: "demoapp-app1-summer"
              servicePort: 80
          - path: /summer/*
            backend:
              serviceName: "demoapp-app1-summer"
              servicePort: 80
          - path: /winter
            backend:
              serviceName: "demoapp-app2-winter"
              servicePort: 80
          - path: /winter/*
            backend:
              serviceName: "demoapp-app2-winter"
              servicePort: 80
          - path: /
            backend:
              serviceName: "codesuite-demo"
              servicePort: 80
          - path: /*
            backend:
              serviceName: "codesuite-demo"
              servicePort: 80
