apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summer
      version: v2
  template:
    metadata:
      labels:
        app: summer
        version: v2
    spec:
      containers:
        - name: summer
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Key West, Florida\",\"Cape Town, South Africa\"]"

---
apiVersion: v1
kind: Service
metadata:
  name: summer-v2
  labels:
    app: summer
    version: v2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: summer
    version: v2
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: summer-v2
  namespace: prod
spec:
  meshName: travel-app
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: summer-v2.prod.svc.cluster.local
