apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demoapp-frontend"
  namespace: "prod"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "demoapp-frontend"
    spec:
      containers:
      - image: 841726648246.dkr.ecr.us-west-2.amazonaws.com/demoapp-frontend:latest
        imagePullPolicy: Always
        name: "demoapp-frontend"
        ports:
        - containerPort: 80