apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "travel-frontend"
  namespace: "prod"
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: "travel-frontend"
    spec:
      containers:
      - image: wiehahne/dockerhubrepo
        imagePullPolicy: Always
        name: "2048"
        ports:
        - containerPort: 80