apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "travel-frontend-ingress"
  namespace: "prod"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: travel-frontend
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-travel-frontend"
              servicePort: 80