apiVersion: v1
kind: Service
metadata:
  name: summer
  labels:
    app: summer
spec:
  ports:
  - port: 9080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: winter
  labels:
    app: winter
spec:
  ports:
  - port: 9080
    name: http
