apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demoapp-app1-summer"
  namespace: "default"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "demoapp-app1-summer"
    spec:
      containers:
      - image: wiehahne/demoapp-app1
        imagePullPolicy: Always
        name: "demoapp-app1-summer"
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 80