apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demoapp-app1-summer"
  namespace: "prod"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "demoapp-app1-summer"
    spec:
      containers:
      - image: wiehahne/demoapp-app1
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service
        imagePullPolicy: Always
        name: "demoapp-app1-summer"
        ports:
        - containerPort: 80