apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demoapp-app1-summer"
  namespace: "prod"
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: "demoapp-app1-summer"
    spec:
      containers:
      - image: wiehahne/demoapp-app1
        imagePullPolicy: Always
        name: "demoapp-app1-summer"
        ports:
        - containerPort: 80