apiVersion: v1
kind: Service
metadata:
  name: "demoapp-app1-summer"
  namespace: "default"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "demoapp-app1-summer"